// This file has been generated by Tauri Specta. Do not edit this file manually.
export type Friend = {
	profileId: string,
	name: string,
};

export type FriendsList = {
	friends?: Friend[],
	incomingRequests?: Friend[],
	outgoingRequests?: Friend[],
};

export type PresenceEntry = {
	profileId: string,
	status: string,
	joinInfo?: PresenceJoinInfo | null,
	lastUpdated?: string | null,
};

export type PresenceJoinInfo = {
	value: string,
	invited: boolean,
};
