pub mod model;
pub mod registry;
pub mod sound;

use std::collections::{HashMap, HashSet};
use std::sync::OnceLock;

use azalea_block::BlockState;

use crate::physics::block_shape::{LocalBox, compute_shape};

/// Compact per-state property map: `(key, value)` pairs sorted by key. States
/// have at most ~10 properties, so binary search on a boxed slice beats a
/// `HashMap` in both footprint and lookup cost.
pub struct PropMap(Box<[(&'static str, &'static str)]>);

impl PropMap {
    fn from_pairs(mut pairs: Vec<(&'static str, &'static str)>) -> Self {
        pairs.sort_unstable_by_key(|&(k, _)| k);
        Self(pairs.into_boxed_slice())
    }

    pub fn get(&self, key: &str) -> Option<&'static str> {
        self.0
            .binary_search_by_key(&key, |&(k, _)| k)
            .ok()
            .map(|i| self.0[i].1)
    }

    pub fn entries(&self) -> impl Iterator<Item = (&'static str, &'static str)> + '_ {
        self.0.iter().copied()
    }
}

/// The two behavior fields the client reads (from vanilla `BlockBehaviour`).
#[derive(Clone, Copy)]
pub struct BlockBehavior {
    pub destroy_time: f32,
    pub requires_correct_tool_for_drops: bool,
}

const DEFAULT_BEHAVIOR: BlockBehavior = BlockBehavior {
    destroy_time: 1.0,
    requires_correct_tool_for_drops: false,
};

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum FluidKind {
    Empty,
    Water,
    Lava,
}

/// Fluid content of a block state, matching vanilla `FluidState`: sources and
/// waterlogged blocks are amount 8; flowing fluid is `8 - level`; falling
/// fluid (level >= 8) renders/behaves as a full column.
#[derive(Clone, Copy)]
pub struct Fluid {
    pub kind: FluidKind,
    pub amount: u8,
    /// Not consumed yet; kept for vanilla parity (falling columns behave as
    /// full sources in flow/height logic).
    #[allow(dead_code)]
    pub falling: bool,
}

const NO_FLUID: Fluid = Fluid {
    kind: FluidKind::Empty,
    amount: 0,
    falling: false,
};

const FULL_WATER: Fluid = Fluid {
    kind: FluidKind::Water,
    amount: 8,
    falling: false,
};

impl Fluid {
    pub fn height(&self) -> f32 {
        self.amount as f32 / 9.0
    }
}

/// Per-state block data loaded from the per-version table generated by
/// `tools/blockgen` from Mojang's data-generator report. Hot paths (meshing
/// classifies and textures every block) index this directly.
struct BlockData {
    id: &'static str,
    properties: PropMap,
    behavior: BlockBehavior,
    /// Collision shape; see `block_shape::partial_shape` for the encoding.
    shape: Option<Box<[LocalBox]>>,
    is_air: bool,
    fluid: Fluid,
}

#[derive(serde::Deserialize)]
struct BlockFile {
    version: String,
    state_count: u32,
    blocks: Vec<BlockEntry>,
}

// The data files also carry a `default_id` per block; nothing client-side
// consumes it yet, so serde skips it.
#[derive(serde::Deserialize)]
struct BlockEntry {
    name: String,
    first_id: u32,
    /// `(key, values)` in state-enumeration order; the last property varies
    /// fastest across consecutive state ids.
    #[serde(default)]
    props: Vec<(String, Vec<String>)>,
}

#[derive(serde::Deserialize)]
struct BehaviorEntry {
    destroy_time: f32,
    requires_correct_tool: bool,
}

static BLOCK_TABLE: OnceLock<Vec<BlockData>> = OnceLock::new();

/// Vanilla getFluidState overrides on blocks without a `waterlogged` property.
const IMPLICIT_WATER: [&str; 4] = ["seagrass", "tall_seagrass", "kelp", "kelp_plant"];

/// Loads the block-state table for the selected game version. Must be called
/// once at startup before any world/render code runs.
pub fn init(version: &str) {
    if version != "26.2" {
        tracing::warn!(
            "no block-state data for version {version}, using 26.2 — expect state drift"
        );
    }
    let _ = BLOCK_TABLE.set(build_table(include_str!("data/blocks-26.2.json")));
}

fn build_table(data: &str) -> Vec<BlockData> {
    let file: BlockFile = serde_json::from_str(data).expect("invalid block-state data");
    let behaviors: HashMap<String, BehaviorEntry> =
        serde_json::from_str(include_str!("data/block_behavior.json"))
            .expect("invalid block-behavior data");

    let mut interner: HashSet<&'static str> = HashSet::new();
    let mut intern = |s: &str| -> &'static str {
        match interner.get(s) {
            Some(&e) => e,
            None => {
                let leaked: &'static str = Box::leak(s.to_string().into_boxed_str());
                interner.insert(leaked);
                leaked
            }
        }
    };

    let mut table: Vec<BlockData> = Vec::with_capacity(file.state_count as usize);
    for block in &file.blocks {
        assert_eq!(
            block.first_id,
            table.len() as u32,
            "block-state data not dense at '{}'",
            block.name
        );
        let name = intern(&block.name);
        let behavior = match behaviors.get(&block.name) {
            Some(b) => BlockBehavior {
                destroy_time: b.destroy_time,
                requires_correct_tool_for_drops: b.requires_correct_tool,
            },
            None => {
                tracing::warn!("no behavior entry for block '{}', using defaults", name);
                DEFAULT_BEHAVIOR
            }
        };
        let props: Vec<(&'static str, Vec<&'static str>)> = block
            .props
            .iter()
            .map(|(k, vs)| (intern(k), vs.iter().map(|v| intern(v)).collect()))
            .collect();
        let is_air = matches!(block.name.as_str(), "air" | "cave_air" | "void_air");

        let count: u32 = props.iter().map(|(_, vs)| vs.len() as u32).product();
        for offset in 0..count {
            let mut pairs = Vec::with_capacity(props.len());
            let mut stride = count;
            for (key, values) in &props {
                stride /= values.len() as u32;
                pairs.push((*key, values[(offset / stride) as usize % values.len()]));
            }
            let properties = PropMap::from_pairs(pairs);
            let fluid = state_fluid(name, &properties);
            let shape = compute_shape(name, &properties).map(Vec::into_boxed_slice);
            table.push(BlockData {
                id: name,
                properties,
                behavior,
                shape,
                is_air,
                fluid,
            });
        }
    }

    assert_eq!(
        table.len() as u32,
        file.state_count,
        "block-state data table size mismatch for {}",
        file.version
    );
    table
}

fn state_fluid(name: &'static str, props: &PropMap) -> Fluid {
    match name {
        "water" | "lava" => {
            let level: u8 = props.get("level").and_then(|l| l.parse().ok()).unwrap_or(0);
            let kind = if name == "water" {
                FluidKind::Water
            } else {
                FluidKind::Lava
            };
            if level >= 8 {
                Fluid {
                    kind,
                    amount: 8,
                    falling: true,
                }
            } else {
                Fluid {
                    kind,
                    amount: 8 - level,
                    falling: false,
                }
            }
        }
        "bubble_column" => FULL_WATER,
        _ if IMPLICIT_WATER.contains(&name) => FULL_WATER,
        _ if props.get("waterlogged") == Some("true") => FULL_WATER,
        _ => NO_FLUID,
    }
}

fn table() -> &'static Vec<BlockData> {
    BLOCK_TABLE
        .get()
        .expect("world::block::init must be called before use")
}

fn block_data(state: BlockState) -> &'static BlockData {
    static UNKNOWN: std::sync::LazyLock<BlockData> = std::sync::LazyLock::new(|| BlockData {
        id: "unknown",
        properties: PropMap::from_pairs(Vec::new()),
        behavior: DEFAULT_BEHAVIOR,
        shape: None,
        is_air: false,
        fluid: NO_FLUID,
    });
    table().get(u32::from(state) as usize).unwrap_or(&UNKNOWN)
}

/// Every valid block state paired with its cached data, in id order.
fn all_states() -> impl Iterator<Item = (BlockState, &'static BlockData)> {
    table().iter().enumerate().map(|(id, data)| {
        let state = BlockState::try_from(id as u32).expect("table indices fit the id repr");
        (state, data)
    })
}

/// Converts a wire-side numeric state id, validated against the loaded table.
pub fn try_state(id: u32) -> Option<BlockState> {
    if (id as usize) < table().len() {
        BlockState::try_from(id).ok()
    } else {
        None
    }
}

pub fn block_id(state: BlockState) -> &'static str {
    block_data(state).id
}

pub fn block_properties(state: BlockState) -> &'static PropMap {
    &block_data(state).properties
}

pub fn block_behavior(state: BlockState) -> &'static BlockBehavior {
    &block_data(state).behavior
}

/// Vanilla `isAir`: includes cave and void air.
pub fn is_air(state: BlockState) -> bool {
    block_data(state).is_air
}

pub fn fluid(state: BlockState) -> Fluid {
    block_data(state).fluid
}

pub(crate) fn block_shape(state: BlockState) -> Option<&'static [LocalBox]> {
    block_data(state).shape.as_deref()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn setup() {
        init("26.2");
    }

    #[test]
    fn chest_states_decode() {
        setup();
        // Oracle from reference/26.2/generated/reports/blocks.json:
        // chest[type=single,facing=south,waterlogged=false] is id 3994 — the
        // state that previously decoded as facing=east under azalea's stale
        // 26.1 tables.
        let state = try_state(3994).unwrap();
        assert_eq!(block_id(state), "chest");
        let props = block_properties(state);
        assert_eq!(props.get("facing"), Some("south"));
        assert_eq!(props.get("type"), Some("single"));
        assert_eq!(props.get("waterlogged"), Some("false"));
    }

    #[test]
    fn new_26_2_blocks_resolve() {
        setup();
        assert!(all_states().any(|(_, d)| d.id == "copper_chest"));
        assert!(try_state(u32::MAX).is_none());
        let count = table().len() as u32;
        assert!(try_state(count).is_none());
        assert!(try_state(count - 1).is_some());
    }

    #[test]
    fn fluid_states() {
        setup();
        let (still, _) = all_states()
            .find(|(s, d)| d.id == "water" && block_properties(*s).get("level") == Some("0"))
            .unwrap();
        let f = fluid(still);
        assert_eq!(f.kind, FluidKind::Water);
        assert_eq!(f.amount, 8);
        assert!(!f.falling);

        let (falling, _) = all_states()
            .find(|(s, d)| d.id == "water" && block_properties(*s).get("level") == Some("9"))
            .unwrap();
        assert!(fluid(falling).falling);

        let (logged, _) = all_states()
            .find(|(s, d)| {
                d.id == "oak_stairs" && block_properties(*s).get("waterlogged") == Some("true")
            })
            .unwrap();
        assert_eq!(fluid(logged).kind, FluidKind::Water);
        assert_eq!(fluid(logged).amount, 8);

        assert_eq!(fluid(BlockState::AIR).kind, FluidKind::Empty);
    }
}
