#version 450

#include "fog.glsl"

layout(set = 0, binding = 0) uniform CameraUniform {
    mat4 view_proj;
    vec4 camera_pos;
    vec4 fog_color;
    // Camera block position; the other fog shaders declare this only as
    // padding for fog_env's offset, this one reads it to rebase origins.
    ivec4 camera_block;
    vec4 fog_env;
};

// POS_RANGE / POS_BIAS, generated by build.rs from packing_consts.rs.
#include "packing.glsl"

layout(location = 0) in vec2 in_pos_xy;
layout(location = 1) in float in_pos_z;
layout(location = 2) in vec2 tex_coords;
layout(location = 3) in vec4 light_tint;
// Per-instance (from the meta buffer):
layout(location = 4) in ivec3 in_origin;
layout(location = 5) in float in_fade;

layout(location = 0) out vec2 v_tex_coords;
layout(location = 1) out float v_light;
layout(location = 2) out vec3 v_tint;
layout(location = 3) flat out float v_visibility;
layout(location = 4) out vec3 v_fog_color;
layout(location = 5) out float v_fog;

void main() {
    vec3 local = vec3(in_pos_xy, in_pos_z) * POS_RANGE - POS_BIAS;
    // Vanilla terrain.vsh: rebase the absolute integer section origin against
    // the camera block position in integer math (exact at any coordinate);
    // camera_pos is the eye's offset from that block position.
    vec3 rel = vec3(in_origin - camera_block.xyz) + local - camera_pos.xyz;
    gl_Position = view_proj * vec4(rel, 1.0);
    v_tex_coords = tex_coords;
    v_light = light_tint.r;
    v_tint = light_tint.gba;
    v_visibility = in_fade;
    v_fog_color = fog_color.rgb;
    v_fog = total_fog_value(rel, fog_env, camera_pos.w, fog_color.w);
}
